//! Act on what [`super::dedup`] found, reclaim the space, without ever risking the data.
//!
//! This is the destructive half of dedup, run against irreplaceable collections, so every design
//! choice here is made in favour of "impossible to lose a file" over "reclaims the most bytes".
//!
//! ## The rules
//!
//! - **Nothing happens without `apply`.** Planning is pure: it reads, decides, and prints. The default
//!   is a dry run, so the destructive path is always opt-in and always previewable.
//! - **Only byte-identical groups are eligible.** [`GroupKind::Similar`] findings are never planned, at
//!   all, for any action; see [`plan`]. Visual similarity cannot distinguish a redundant re-encode
//!   from two real photographs.
//! - **Every group keeps a copy.** One member is chosen as the keeper by an explicit, deterministic
//!   [`KeepPolicy`]; only the others are ever touched.
//! - **Re-verified immediately before acting.** A scan can finish hours before anyone types `--apply`,
//!   so size and full BLAKE3 are checked *again* at the moment of action. A file that changed in the
//!   meantime is skipped, never acted on.
//! - **Nothing is deleted.** The two actions are replacing a duplicate with a hard link to the keeper
//!   (same bytes, every filename and folder preserved), or *moving* it to a quarantine directory the
//!   user deletes themselves once satisfied. There is no code path in this module that deletes a
//!   user's file outright.
//!
//! ## Hard links, and their one caveat
//!
//! [`Action::Link`] leaves every path exactly where it was, the folder structure of a photo
//! collection often *is* the meaning, so nothing disappears from view; while the redundant copies
//! stop occupying space. The caveat, which callers must surface: linked paths are one file, so an
//! editor that rewrites a photo **in place** changes it under every name. Tools that write a new file
//! (the overwhelmingly common case) are unaffected. Quarantine is the alternative when that matters.

use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};

use super::dedup::{
    hash_whole, same_physical_file, volume_of, DedupReport, GroupKind, ScannedFile,
};
use crate::error::{ArchiveError, Result};
use crate::progress::ProgressSink;

/// Which copy of a duplicate set to keep. Every policy breaks ties by path, so a plan is reproducible:
/// running twice over an unchanged collection produces exactly the same decisions.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum KeepPolicy {
    /// Names that look auto-generated by a copy (`Copy of x`, `x (2)`) lose first; then fewest path
    /// components, then shortest path text. Tends to keep a tidy `photos/x.jpg` over
    /// `misc/unsorted/Copy of Copy of x.jpg`.
    ///
    /// No heuristic can know which folder a person considers canonical, so with
    /// [`Action::Quarantine`], where the keeper is the copy that stays put; the chosen keeper is
    /// printed in the preview for exactly that reason.
    #[default]
    ShortestPath,
    /// Earliest modification time, the closest thing to "the original" when copies were made later.
    Oldest,
    /// First in path order. Dumb, total, and utterly predictable.
    First,
}

/// What to do with a redundant copy.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Action {
    /// Replace it with a hard link to the keeper. Requires both to be on one filesystem.
    Link,
    /// Move it into the quarantine directory, preserving its original path underneath.
    Quarantine,
}

/// One decided operation. `bytes` is what this single action frees.
#[derive(Clone, Debug)]
pub struct PlannedAction {
    pub keeper: PathBuf,
    pub victim: PathBuf,
    pub action: Action,
    pub bytes: u64,
    /// Where the victim will be moved (quarantine only).
    pub dest: Option<PathBuf>,
}

/// The full set of decisions, plus everything deliberately left alone and why.
#[derive(Clone, Debug, Default)]
pub struct Plan {
    pub actions: Vec<PlannedAction>,
    /// Files not planned for any action, with the reason; shown so a dry run is honest about its gaps
    /// rather than silently reclaiming less than the scan promised.
    pub skipped: Vec<(PathBuf, String)>,
}

impl Plan {
    /// Bytes freed if the whole plan is applied.
    pub fn bytes(&self) -> u64 {
        self.actions.iter().map(|a| a.bytes).sum()
    }
    pub fn links(&self) -> usize {
        self.actions
            .iter()
            .filter(|a| a.action == Action::Link)
            .count()
    }
    pub fn quarantines(&self) -> usize {
        self.actions
            .iter()
            .filter(|a| a.action == Action::Quarantine)
            .count()
    }
}

/// How to turn a report into a plan.
#[derive(Clone, Debug, Default)]
pub struct ReclaimOptions {
    /// Replace same-filesystem duplicates with hard links.
    pub link: bool,
    /// Move duplicates here when a hard link is impossible (or when linking is not requested).
    pub quarantine: Option<PathBuf>,
    pub keep: KeepPolicy,
}

/// What actually happened.
#[derive(Clone, Debug, Default)]
pub struct ReclaimReport {
    pub linked: u64,
    pub quarantined: u64,
    pub bytes_reclaimed: u64,
    /// Actions abandoned because the files no longer matched at the moment of truth.
    pub skipped_changed: u64,
    /// Actions that failed, with the reason. A failure here never leaves data destroyed, see the
    /// transaction in [`replace_with_hardlink`].
    pub failed: Vec<(PathBuf, String)>,
    pub cancelled: bool,
}

/// Decide what to do, touching nothing.
///
/// **Only [`GroupKind::Exact`] groups are ever considered.** That filter is the single most important
/// line in this module: it is what keeps perceptual "similar" findings, which may be different
/// photographs, permanently out of reach of anything destructive.
pub fn plan(report: &DedupReport, opts: &ReclaimOptions) -> Plan {
    let mut out = Plan::default();
    for group in report.groups.iter().filter(|g| g.kind == GroupKind::Exact) {
        if group.files.len() < 2 {
            continue;
        }
        let keeper = match choose_keeper(&group.files, opts.keep) {
            Some(k) => k,
            None => continue,
        };
        for victim in &group.files {
            if victim.path == keeper.path {
                continue;
            }
            // Already one file under two names: linking it again would free nothing and the "saving"
            // would be fictional.
            if same_physical_file(&keeper.path, &victim.path) {
                continue;
            }
            let same_volume = volume_of(&keeper.path) == volume_of(&victim.path);
            let action = if opts.link && same_volume {
                Some(Action::Link)
            } else if opts.quarantine.is_some() {
                Some(Action::Quarantine)
            } else {
                None
            };
            match action {
                Some(Action::Link) => out.actions.push(PlannedAction {
                    keeper: keeper.path.clone(),
                    victim: victim.path.clone(),
                    action: Action::Link,
                    bytes: victim.size,
                    dest: None,
                }),
                Some(Action::Quarantine) => {
                    let qdir = opts.quarantine.as_ref().expect("checked above");
                    out.actions.push(PlannedAction {
                        keeper: keeper.path.clone(),
                        victim: victim.path.clone(),
                        action: Action::Quarantine,
                        bytes: victim.size,
                        dest: Some(quarantine_dest(qdir, &victim.path)),
                    });
                }
                None => out.skipped.push((
                    victim.path.clone(),
                    if opts.link && !same_volume {
                        "on a different drive from the copy being kept, a hard link cannot span \
                         filesystems; use --quarantine as well"
                            .into()
                    } else {
                        "no action requested (pass --link and/or --quarantine)".into()
                    },
                )),
            }
        }
    }
    out.actions.sort_by(|a, b| a.victim.cmp(&b.victim));
    out
}

/// Pick the copy to keep. Ties always fall through to path order, so the choice is deterministic.
fn choose_keeper(files: &[ScannedFile], policy: KeepPolicy) -> Option<&ScannedFile> {
    match policy {
        KeepPolicy::First => files.iter().min_by(|a, b| a.path.cmp(&b.path)),
        KeepPolicy::ShortestPath => files.iter().min_by(|a, b| {
            // `false < true`, so a name that is obviously an auto-generated copy loses to one that
            // is not, before path length is even considered.
            looks_like_a_copy(&a.path)
                .cmp(&looks_like_a_copy(&b.path))
                .then_with(|| {
                    a.path
                        .components()
                        .count()
                        .cmp(&b.path.components().count())
                })
                .then_with(|| a.path.as_os_str().len().cmp(&b.path.as_os_str().len()))
                .then_with(|| a.path.cmp(&b.path))
        }),
        KeepPolicy::Oldest => files.iter().min_by(|a, b| {
            let t = |f: &ScannedFile| fs::metadata(&f.path).and_then(|m| m.modified()).ok();
            match (t(a), t(b)) {
                (Some(x), Some(y)) => x.cmp(&y).then_with(|| a.path.cmp(&b.path)),
                // An unreadable timestamp must not win by accident; fall back to path order.
                _ => a.path.cmp(&b.path),
            }
        }),
    }
}

/// Does this filename look auto-generated by a copy operation rather than being an original?
///
/// Windows, macOS and most file managers mint `Copy of x`, `x - Copy` and `x (2)` when duplicating,
/// and those are exactly the copies a person would choose to lose. Only the *filename* is examined,
/// guessing from folder names ("backup", "unsorted") misfires on people who legitimately organise that
/// way. This only ever breaks a tie in [`KeepPolicy::ShortestPath`]; it can never cause an action that
/// would not otherwise happen.
fn looks_like_a_copy(path: &Path) -> bool {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_lowercase())
        .unwrap_or_default();
    if name.contains("copy") || name.contains("duplicate") {
        return true;
    }
    // A trailing parenthesised number, "photo (2).jpg", is the near-universal auto-rename.
    let stem = path
        .file_stem()
        .map(|s| s.to_string_lossy().trim_end().to_string())
        .unwrap_or_default();
    if let Some(open) = stem.strip_suffix(')').and_then(|s| s.rfind('(')) {
        let inner = &stem[open + 1..stem.len() - 1];
        return !inner.is_empty() && inner.chars().all(|c| c.is_ascii_digit());
    }
    false
}

/// Where a quarantined file lands: the original path rebuilt under the quarantine root, so what was
/// moved, and where it came from, stays obvious, and putting it back is a plain move.
fn quarantine_dest(qdir: &Path, victim: &Path) -> PathBuf {
    let mut dest = qdir.to_path_buf();
    for c in victim.components() {
        match c {
            // `D:` → `D`, so the drive stays visible without an illegal `:` in the new path.
            Component::Prefix(p) => {
                let s: String = p
                    .as_os_str()
                    .to_string_lossy()
                    .chars()
                    .filter(|c| c.is_alphanumeric())
                    .collect();
                if !s.is_empty() {
                    dest.push(s);
                }
            }
            Component::Normal(n) => dest.push(n),
            Component::RootDir | Component::CurDir | Component::ParentDir => {}
        }
    }
    dest
}

/// Carry out a plan. Each action re-verifies its pair immediately beforehand and is skipped, never
/// forced, if reality has moved on since the scan.
pub fn apply(plan: &Plan, sink: &dyn ProgressSink) -> Result<ReclaimReport> {
    let mut rep = ReclaimReport::default();
    for act in &plan.actions {
        if sink.is_cancelled() {
            rep.cancelled = true;
            break;
        }
        sink.wait_if_paused();

        match verify_pair(&act.keeper, &act.victim) {
            Ok(Some(hash)) => match run_action(act, &hash) {
                Ok(()) => {
                    match act.action {
                        Action::Link => rep.linked += 1,
                        Action::Quarantine => rep.quarantined += 1,
                    }
                    rep.bytes_reclaimed += act.bytes;
                    sink.on_bytes(act.bytes);
                }
                Err(e) => rep.failed.push((act.victim.clone(), e.to_string())),
            },
            // Not identical any more (or one of them vanished): leave it completely alone.
            Ok(None) => rep.skipped_changed += 1,
            Err(e) => rep.failed.push((act.victim.clone(), e.to_string())),
        }
    }
    Ok(rep)
}

/// The moment-of-truth check. Returns the shared hash when the two files are *still* byte-identical,
/// `None` when they are not (so the caller skips), and an error only when they could not be read.
///
/// Sizes are compared first because that rules out most drift for free, and a full hash of both files
/// follows, the scan's verdict is deliberately not trusted here, however recent it is.
fn verify_pair(keeper: &Path, victim: &Path) -> io::Result<Option<[u8; 32]>> {
    let (mk, mv) = (fs::metadata(keeper)?, fs::metadata(victim)?);
    if !mk.is_file() || !mv.is_file() || mk.len() != mv.len() {
        return Ok(None);
    }
    let hk = hash_whole(keeper)?;
    let hv = hash_whole(victim)?;
    Ok((hk == hv).then_some(hv))
}

fn run_action(act: &PlannedAction, hash: &[u8; 32]) -> io::Result<()> {
    match act.action {
        Action::Link => replace_with_hardlink(&act.keeper, &act.victim),
        Action::Quarantine => {
            let dest = act.dest.clone().ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "quarantine action without a destination",
                )
            })?;
            move_to_quarantine(&act.victim, &dest, hash)
        }
    }
}

/// Replace `victim` with a hard link to `keeper`, transactionally.
///
/// The link is built under a temporary name **first**, so the original is still intact if creating it
/// fails. On Unix the swap is then a single atomic `rename`, and there is no instant at which `victim`
/// does not exist. Windows will not rename onto an existing file, so the original is moved aside and
/// removed only once the link is in place; if anything fails it is moved straight back.
fn replace_with_hardlink(keeper: &Path, victim: &Path) -> io::Result<()> {
    let tmp = sibling_temp(victim, "link");
    let _ = fs::remove_file(&tmp);
    fs::hard_link(keeper, &tmp)?;

    #[cfg(unix)]
    {
        match fs::rename(&tmp, victim) {
            Ok(()) => Ok(()),
            Err(e) => {
                let _ = fs::remove_file(&tmp);
                Err(e)
            }
        }
    }
    #[cfg(not(unix))]
    {
        let backup = sibling_temp(victim, "old");
        let _ = fs::remove_file(&backup);
        if let Err(e) = fs::rename(victim, &backup) {
            let _ = fs::remove_file(&tmp);
            return Err(e);
        }
        match fs::rename(&tmp, victim) {
            Ok(()) => {
                let _ = fs::remove_file(&backup);
                Ok(())
            }
            Err(e) => {
                // Put the original back exactly where it was before giving up.
                let _ = fs::rename(&backup, victim);
                let _ = fs::remove_file(&tmp);
                Err(e)
            }
        }
    }
}

/// Move `victim` into quarantine. A plain rename when the destination is on the same filesystem;
/// otherwise copy, **verify the copy against `expect`**, and only then remove the original, so an
/// interrupted or corrupted cross-drive move can never destroy the only good copy.
fn move_to_quarantine(victim: &Path, dest: &Path, expect: &[u8; 32]) -> io::Result<()> {
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    let dest = unique_dest(dest);
    if fs::rename(victim, &dest).is_ok() {
        return Ok(());
    }
    // Cross-filesystem (or a rename the OS refused): fall back to copy-verify-delete.
    fs::copy(victim, &dest)?;
    match hash_whole(&dest) {
        Ok(got) if &got == expect => fs::remove_file(victim),
        Ok(_) => {
            let _ = fs::remove_file(&dest);
            Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "the quarantine copy did not match the original; the original was left untouched",
            ))
        }
        Err(e) => {
            let _ = fs::remove_file(&dest);
            Err(e)
        }
    }
}

/// A destination that does not collide with something already quarantined from elsewhere.
fn unique_dest(dest: &Path) -> PathBuf {
    if !dest.exists() {
        return dest.to_path_buf();
    }
    let stem = dest
        .file_stem()
        .unwrap_or_default()
        .to_string_lossy()
        .into_owned();
    let ext = dest.extension().map(|e| e.to_string_lossy().into_owned());
    let parent = dest.parent().unwrap_or(Path::new("."));
    for n in 2..10_000u32 {
        let name = match &ext {
            Some(e) => format!("{stem} ({n}).{e}"),
            None => format!("{stem} ({n})"),
        };
        let cand = parent.join(name);
        if !cand.exists() {
            return cand;
        }
    }
    dest.to_path_buf()
}

/// A scratch name beside `path`, same directory, therefore same filesystem, so the rename that
/// follows is a metadata operation rather than a copy.
fn sibling_temp(path: &Path, tag: &str) -> PathBuf {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    let parent = path.parent().unwrap_or(Path::new("."));
    parent.join(format!(".{name}.cram-{tag}-{}", std::process::id()))
}

/// Reject a plan that would leave a group with no copies at all. A belt-and-braces check over
/// [`plan`]'s own logic: the keeper is excluded from the victim list by construction, but this is the
/// invariant whose violation would be unrecoverable, so it is asserted rather than assumed.
pub fn validate(plan: &Plan) -> Result<()> {
    for act in &plan.actions {
        if act.keeper == act.victim {
            return Err(ArchiveError::Backend(format!(
                "refusing to act: the plan would consume the copy it keeps ({})",
                act.victim.display()
            )));
        }
    }
    let victims: std::collections::HashSet<&PathBuf> =
        plan.actions.iter().map(|a| &a.victim).collect();
    for act in &plan.actions {
        if victims.contains(&act.keeper) {
            return Err(ArchiveError::Backend(format!(
                "refusing to act: {} is kept by one action and consumed by another",
                act.keeper.display()
            )));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::dedup::{scan, DedupOptions};
    use crate::progress::Progress;
    use std::io::Write;

    fn scratch(name: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("cram-reclaim-{}-{}", name, std::process::id()));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).unwrap();
        d
    }
    fn write(path: &Path, bytes: &[u8]) {
        if let Some(p) = path.parent() {
            fs::create_dir_all(p).unwrap();
        }
        fs::File::create(path).unwrap().write_all(bytes).unwrap();
    }
    fn scan_dir(dir: &Path) -> DedupReport {
        let sink = Progress::new(0, 0);
        scan(
            std::slice::from_ref(&dir.to_path_buf()),
            &DedupOptions::default(),
            &sink,
        )
        .unwrap()
    }

    #[test]
    fn linking_frees_space_but_keeps_every_path_and_its_content() {
        // The core promise for a photo collection: nothing disappears from where it was.
        let dir = scratch("link");
        let photo = vec![0x2Bu8; 400 * 1024];
        for p in ["a/IMG_1.jpg", "b/copy.jpg", "c/deep/another.jpg"] {
            write(&dir.join(p), &photo);
        }
        let rep = scan_dir(&dir);
        let plan = plan(
            &rep,
            &ReclaimOptions {
                link: true,
                ..Default::default()
            },
        );
        validate(&plan).unwrap();
        assert_eq!(plan.actions.len(), 2, "two of three copies are redundant");
        assert_eq!(plan.links(), 2);

        let sink = Progress::new(0, 0);
        let done = apply(&plan, &sink).unwrap();
        assert_eq!(done.linked, 2);
        assert!(done.failed.is_empty(), "failures: {:?}", done.failed);

        // Every original path still exists and still reads back correctly.
        for p in ["a/IMG_1.jpg", "b/copy.jpg", "c/deep/another.jpg"] {
            let got = fs::read(dir.join(p)).unwrap();
            assert_eq!(got, photo, "{p} must still be readable and identical");
        }
        // And a re-scan now sees them as one physical file, so there is nothing left to reclaim.
        #[cfg(unix)]
        {
            let again = scan_dir(&dir);
            assert_eq!(again.reclaimable(), 0, "space is genuinely reclaimed");
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_file_changed_since_the_scan_is_never_touched() {
        // The reason the pair is re-hashed at the moment of action: a stale plan must not be trusted.
        let dir = scratch("changed");
        let a = dir.join("a.bin");
        let b = dir.join("b.bin");
        write(&a, &vec![1u8; 300 * 1024]);
        write(&b, &vec![1u8; 300 * 1024]);
        let rep = scan_dir(&dir);
        let plan = plan(
            &rep,
            &ReclaimOptions {
                link: true,
                ..Default::default()
            },
        );
        assert_eq!(plan.actions.len(), 1);

        // Someone edits one of them between the scan and the apply.
        write(&b, &vec![9u8; 300 * 1024]);

        let sink = Progress::new(0, 0);
        let done = apply(&plan, &sink).unwrap();
        assert_eq!(done.linked, 0, "must not act on a changed file");
        assert_eq!(done.skipped_changed, 1);
        assert_eq!(
            fs::read(&b).unwrap(),
            vec![9u8; 300 * 1024],
            "edit survives"
        );
        assert_eq!(
            fs::read(&a).unwrap(),
            vec![1u8; 300 * 1024],
            "keeper untouched"
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn similar_groups_are_never_planned() {
        // The invariant that keeps perceptual matches away from anything destructive.
        let report = DedupReport {
            groups: vec![crate::engine::dedup::DupeGroup {
                kind: GroupKind::Similar,
                files: vec![
                    ScannedFile {
                        path: PathBuf::from("/x/one.jpg"),
                        size: 10,
                        id: None,
                    },
                    ScannedFile {
                        path: PathBuf::from("/x/two.jpg"),
                        size: 10,
                        id: None,
                    },
                ],
                reclaimable: 0,
            }],
            ..Default::default()
        };
        let p = plan(
            &report,
            &ReclaimOptions {
                link: true,
                quarantine: Some(PathBuf::from("/tmp/q")),
                keep: KeepPolicy::First,
            },
        );
        assert!(p.actions.is_empty(), "similar groups must never be planned");
        assert_eq!(p.bytes(), 0);
    }

    #[test]
    fn quarantine_moves_the_file_and_keeps_it_recoverable() {
        let dir = scratch("quar");
        let q = scratch("quar-store");
        let blob = vec![0x77u8; 200 * 1024];
        // Named so the KeepPolicy::First (alphabetical) outcome is unmistakable: `aaa-keep` sorts
        // first and is therefore the keeper, `zzz-dupes` is the copy that gets quarantined.
        write(&dir.join("aaa-keep/orig.bin"), &blob);
        write(&dir.join("zzz-dupes/copy.bin"), &blob);

        let rep = scan_dir(&dir);
        let plan = plan(
            &rep,
            &ReclaimOptions {
                link: false,
                quarantine: Some(q.clone()),
                keep: KeepPolicy::First,
            },
        );
        assert_eq!(plan.quarantines(), 1);
        let sink = Progress::new(0, 0);
        let done = apply(&plan, &sink).unwrap();
        assert_eq!(done.quarantined, 1);
        assert!(done.failed.is_empty(), "failures: {:?}", done.failed);

        // The keeper survives; the duplicate is gone from its old path but present in quarantine.
        assert!(
            dir.join("aaa-keep/orig.bin").exists(),
            "the keeper must survive"
        );
        assert!(
            !dir.join("zzz-dupes/copy.bin").exists(),
            "the copy is moved away"
        );
        let moved: Vec<PathBuf> = walk_files(&q);
        assert_eq!(moved.len(), 1, "exactly one file quarantined");
        assert_eq!(
            fs::read(&moved[0]).unwrap(),
            blob,
            "quarantined bytes intact"
        );
        let _ = fs::remove_dir_all(&dir);
        let _ = fs::remove_dir_all(&q);
    }

    #[test]
    fn keeper_policy_picks_the_tidiest_path_and_is_stable() {
        let files = vec![
            ScannedFile {
                path: PathBuf::from("/root/misc/unsorted/Copy of Copy of x.jpg"),
                size: 1,
                id: None,
            },
            ScannedFile {
                path: PathBuf::from("/root/photos/x.jpg"),
                size: 1,
                id: None,
            },
        ];
        let k = choose_keeper(&files, KeepPolicy::ShortestPath).unwrap();
        assert_eq!(k.path, PathBuf::from("/root/photos/x.jpg"));
        // Deterministic: the same input always yields the same keeper.
        let again = choose_keeper(&files, KeepPolicy::ShortestPath).unwrap();
        assert_eq!(k.path, again.path);
    }

    #[test]
    fn validate_rejects_a_plan_that_would_consume_its_own_keeper() {
        let bad = Plan {
            actions: vec![
                PlannedAction {
                    keeper: PathBuf::from("/a"),
                    victim: PathBuf::from("/b"),
                    action: Action::Link,
                    bytes: 1,
                    dest: None,
                },
                // /a is kept above but consumed here, applying both could destroy the last copy.
                PlannedAction {
                    keeper: PathBuf::from("/c"),
                    victim: PathBuf::from("/a"),
                    action: Action::Link,
                    bytes: 1,
                    dest: None,
                },
            ],
            skipped: vec![],
        };
        assert!(validate(&bad).is_err());
    }

    fn walk_files(dir: &Path) -> Vec<PathBuf> {
        let mut out = Vec::new();
        if let Ok(rd) = fs::read_dir(dir) {
            for e in rd.flatten() {
                let p = e.path();
                if p.is_dir() {
                    out.extend(walk_files(&p));
                } else {
                    out.push(p);
                }
            }
        }
        out
    }
}
